apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "app-prod-web-ip"
    networking.gke.io/managed-certificates: "web-managed-cert"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - host: WEB_DOMAIN   # replaced per environment
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: web-managed-cert
  namespace: prod
spec:
  domains:
    - WEB_DOMAIN   # replaced per environment
