apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: prod
  annotations:
    # Workload Identity — maps to GCP SA created by Terraform
    iam.gke.io/gcp-service-account: WEB_WORKLOAD_SA_EMAIL
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: prod
  annotations:
    iam.gke.io/gcp-service-account: API_WORKLOAD_SA_EMAIL
